package constant

// General
const (
	APP_HOST    = "APP_HOST"
	APP_VERSION = "APP_VERSION"
	APP_NAME    = "APP_NAME"
	APP_PORT    = "APP_PORT"
	APP_ENV     = "APP_ENV"

	JWT_KEY = "JWT_KEY"
)

// Db
const (
	DB_HOST       = "DB_HOST"
	DB_USER       = "DB_USER"
	DB_PASS       = "DB_PASS"
	DB_PORT       = "DB_PORT"
	DB_NAME       = "DB_NAME"
	DB_SSLMODE    = "DB_SSLMODE"
	DB_TZ         = "DB_TZ"
	DB_CHARSET    = "DB_CHARSET"
	DB_PARSE_TIME = "DB_PARSE_TIME"
	DB_LOCATION   = "DB_LOCATION"

	MIGRATION_ENABLED = "MIGRATION_ENABLED"
	SEEDER_ENABLED    = "SEEDER_ENABLED"

	DB_MAX_OPEN_CONN = "DB_MAX_OPEN_CONN"
	DB_MAX_IDLE_CONN = "DB_MAX_IDLE_CONN"
	DB_MAX_LIFETIME  = "DB_MAX_LIFETIME"
)
